import Head from 'next/head';
import { type Children } from '../common/types';
import Navbar from '../navbar';
import { AuthProvider } from '@/common/hooks/useAuth';

type Props = {};

const PrivateLayout = ({ children }: Props & Children) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/images/favicon.ico' />
      </Head>
      <Navbar />
      <main className='flex-grow container m-auto'>
        <AuthProvider>{children}</AuthProvider>
      </main>
    </>
  );
};

export default PrivateLayout;
